### ISSUE TITLE
Questions about the calendar and authentication

### ISSUE THREAD

**Issue by kerremann** [jitsi/jitsi-meet-spot#1043]
I have two questions about Spot.

- Is there a way to use on prem Exchange calendar?
- does spot have support for JWT authentication?

**Comment by saghul** [comment]
> * Is there a way to use on prem Exchange calendar?

Yes, but you'd need to write a little web servcie that talks to the Exchange calendar and exposes it to Spot.

> * does spot have support for JWT authentication?

Yes. In such scenario you'll want to use a pairing service.

We do provide sample implementations in the spot-admin repo.
