### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by RenatoCaenaro** [jitsi/jitsi-meet-spot#913]
Hello, is this project alive? Any docs about installation process?

thx!

**Comment by saghul** [comment]
We have no timeline, but we do expect to pick it back up.

**Comment by saghul** [comment]
> I would really love to see this project also alive!

As I said, it still is!



> I'm very interested in using this, but can't seem to get it to work.

What have you tried?



> Is it also running somewhere to test its functionality?

The simplest way to test it to run spot-client in development mode, which targets alpha.jitsi.net. Please don't make serious use of it.



> I saw https://spot.jitsi.net/tv but that only gives me the request for a pairing code.
> I can't seem to find how to get a pairing code.

That is our prod instance, you cannot get a pairing code there :-)

**Comment by normanu** [comment]
I actually got a bit further in getting the Spot client working.
It automaticly as a standard connects to Alpha.jitsi.net

For some reason clients videos are not shown, only the screen can be shared.
It auto defaults to tile mode also when sharing a screen, so on screen sharing its not in full screen.
I tried changing the meeting join URL bij changing the config.js but I can't seem to change it.
It stays fixed to the above standard.
Same I tried to get the calendar to connect to a URL and show the planning but unfortunately it does not.
What is wrong in the below config.js if I want to change it from alpha.jitsi.net to meet.jit.si (will be own server in future)

`
window.JitsiMeetSpotConfig = {
    // Example override:
    DEFAULT_DOMAIN = 'meet.jit.si',
    DEFAULT_MEETING_DOMAIN = 'meet.jit.si',
    MEETING_DOMAINS_WHITELIST: [ 'meet.jit.si'],
    CALENDARS: {
        BACKEND: {
            SERVICE_URL: [ 'https://<URL>/SOGo/dav/public/Meetingroom@<DOMAIN>.nl/Calendar/personal.ics' ]
        }
    }
    SPOT_SERVICES: {
        jwtDomains: [ 'meet.jit.si']
    }
};
`

Also how would you configure the permanent remote?
Would the setup be a PC connected to the TV and use a tablet as a remote?

**Comment by saghul** [comment]
> For some reason clients videos are not shown, only the screen can be shared.

Spot client represents a physical room. You need to join the other participants from a different browser instance / computer. Or do you not see them even though they are in the meeting and have video turned on?



> It auto defaults to tile mode also when sharing a screen, so on screen sharing its not in full screen.

How many participants did you test this with? Were you using remote screen sharing or was a participant in the meeting sharing their screen?



> I tried changing the meeting join URL bij changing the config.js but I can't seem to change it.
> It stays fixed to the above standard.

Not sure what you mean here.



> Same I tried to get the calendar to connect to a URL and show the planning but unfortunately it does not.

You need a backend service for it. There should be a sample / API docs in the repo. Client side calendar support got removed.




> What is wrong in the below config.js if I want to change it from alpha.jitsi.net to meet.jit.si (will be own server in future)
> 
> `window.JitsiMeetSpotConfig = { // Example override: DEFAULT_DOMAIN = 'meet.jit.si', DEFAULT_MEETING_DOMAIN = 'meet.jit.si', MEETING_DOMAINS_WHITELIST: [ 'meet.jit.si'], CALENDARS: { BACKEND: { SERVICE_URL: [ 'https://<URL>/SOGo/dav/public/Meetingroom@<DOMAIN>.nl/Calendar/personal.ics' ] } } SPOT_SERVICES: { jwtDomains: [ 'meet.jit.si'] } };`

Pointing it at an ICS won't do alas. You need to provide a backend, and we don't currently have a generic implementation.

For it to work on your own instance you'll need to change the XMPP connection settings to also point to your instance.



> Also how would you configure the permanent remote?

That requires a pairing service. There is a sample one IIRC here in spot-admin. Though you don't need it, ad-hoc pairing should work just fine.



> Would the setup be a PC connected to the TV and use a tablet as a remote?

Yep, that's our usual setup.
